name: Check Env Variable from Issue

on:
  issues:
    types: [opened]

jobs:
  action_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make the script executable
        run: chmod +x ./scripts/script.sh
      - name: run script
        env:
          USER: ${{ github.event.issue.body }}
        run : ./scripts/script.sh $USER
