name: Create user from Issue

on:
  issues:
    types: [opened]

jobs:
  action_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make the script executable
        run: chmod +x ./scripts/script_user_verification.sh
      - name: check script
        id: check_script
        env:
          USER: ${{ github.event.issue.body }}
        run: |
        
          SCRIPT_RESULT=$(./scripts/script_user_verification.sh $USER)
          
          if [[ $SCRIPT_RESULT == $USER ]]; then
             echo "run Ansible GOOD!!" 
          else
             echo $SCRIPT_RESULT
          fi
        
