name: Check Env Variable from Issue

on:
  issues:
    types: [opened]

jobs:
  action_job:
    runs-on: ubuntu-latest
    steps:
      - name: if user
        env:
          USER: ${{ env.MY_VARIABLE }}
      - if: ${{ env.MY_VARIABLE == '' }}
        run: |
          echo "Text: '$env_var'
      - if: ${{ env.USER != '' }}
        run: |
          echo "Text: '$USER'"
