name: Check Env Variable from Issue

on:
  issues:
    types: [opened]

jobs:
  action_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: if user
        env:
          USER: ${{ env.MY_VARIABLE }}
        run: |
          echo "Text: '$USER'"
