name: Check Env Variable from Issue

on:
  issues:
    types: [opened]

env:
  USER: ${{ env.MY_VARIABLE }}
jobs:
  action_job:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ env.MY_VARIABLE == '' }}
        run: |
          echo "Text: '$env_var'
      - if: ${{ env.USER != '' }}
        run: |
          echo "Text: '$USER'"
