name: Check Env Variable from Issue

on:
  issues:
    types: [opened]

jobs:
  action_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make the script executable
        run: chmod +x ./scripts/script_user_verification.sh
      - name: run script
        env:
          USER: ${{ github.event.issue.body }}
        run: |
          SCRIPT_RESULT=$(./scripts/script_user_verification.sh $USER)
          
          if [ $SCRIPT_RESULT != $USER ]; then
            echo $SCRIPT_RESULT
            exit 1
          fi
          
          if [ $SCRIPT_RESULT == $USER ]; then
            echo "USER_NAME=$SCRIPT_RESULT" >> $GITHUB_ENV
            exit 1
          fi

      - name: Run Ansible playbook
        if: ${{ env.USER_NAME != '' }}
        run: |
          "echo run Future Ansuble play"
